# -*- coding: utf-8 -*-
"""World Happiness Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qmh3s2gwCFQxv-Yg8DYdEXpX-LKTotk
"""

#The dataset used in this analysis is sourced from the official World Happiness Report 2021, which focuses on the effects of COVID-19 and how people worldwide have fared.
# Install necessary libraries
!pip install pandas matplotlib seaborn

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set visualization styles
sns.set(style='whitegrid')
plt.rcParams['figure.figsize'] = (12, 8)

# Load the dataset
url = "https://raw.githubusercontent.com/Explore-AI/Public-Data/master/world-happiness-report-2021.csv"
df = pd.read_csv(url)

# Display basic information
print("First 5 rows of the dataset:")
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())

# Rename columns for consistency
df.columns = df.columns.str.replace(" ", "_").str.lower()

# Check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# Correlation Matrix
corr = df.corr(numeric_only=True)

# Heatmap of correlation
plt.figure(figsize=(14, 10))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix of World Happiness Factors (2021)")
plt.show()

# Top 10 Happiest Countries
top_10 = df.sort_values(by='ladder_score', ascending=False).head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x='ladder_score', y='country_name', data=top_10, palette='viridis')
plt.title('Top 10 Happiest Countries in 2021')
plt.xlabel('Happiness Score')
plt.ylabel('Country')
plt.show()

# Bottom 10 Least Happy Countries
bottom_10 = df.sort_values(by='ladder_score', ascending=True).head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x='ladder_score', y='country_name', data=bottom_10, palette='rocket')
plt.title('Bottom 10 Least Happy Countries in 2021')
plt.xlabel('Happiness Score')
plt.ylabel('Country')
plt.show()

# GDP vs Happiness Score
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='logged_gdp_per_capita', y='ladder_score', hue='regional_indicator', palette='Set2', s=100, alpha=0.7)
plt.title('Happiness Score vs GDP per Capita')
plt.xlabel('Log GDP per Capita')
plt.ylabel('Happiness Score')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# Social Support vs Happiness
plt.figure(figsize=(10, 6))
sns.regplot(data=df, x='social_support', y='ladder_score', scatter_kws={'alpha':0.5})
plt.title('Social Support vs Happiness Score')
plt.xlabel('Social Support')
plt.ylabel('Happiness Score')
plt.show()

# Freedom vs Happiness
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='freedom_to_make_life_choices', y='ladder_score', hue='regional_indicator', palette='tab10')
plt.title('Freedom to Make Life Choices vs Happiness')
plt.xlabel('Freedom')
plt.ylabel('Happiness Score')
plt.show()

# Regional Happiness Distribution
plt.figure(figsize=(14, 6))
sns.boxplot(data=df, x='regional_indicator', y='ladder_score', palette='pastel')
plt.xticks(rotation=45)
plt.title('Happiness Score Distribution by Region')
plt.ylabel('Happiness Score')
plt.xlabel('Region')
plt.show()

# Key Insights
print("\n🔍 Key Observations:")
print("- Countries with higher GDP, strong social support, and greater freedom tend to have higher happiness scores.")
print("- Northern and Western Europe countries dominate the top ranks.")
print("- War-torn or economically unstable countries fall into the least happy group.")